// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/SuKaiFei/go-wxxcx/internal/biz"
	"github.com/SuKaiFei/go-wxxcx/internal/conf"
	"github.com/SuKaiFei/go-wxxcx/internal/data"
	"github.com/SuKaiFei/go-wxxcx/internal/server"
	"github.com/SuKaiFei/go-wxxcx/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, application *conf.Application, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	biaoQingBaoRepo := data.NewBqbRepo(dataData, logger)
	biaoQingBaoUseCase := biz.NewBiaoQingBaoUseCase(biaoQingBaoRepo, logger)
	bqbService := service.NewBqbService(biaoQingBaoUseCase)
	voiceRepo := data.NewVoiceRepo(dataData, logger)
	voiceUseCase := biz.NewVoiceUseCase(voiceRepo, logger)
	voiceService := service.NewVoiceService(voiceUseCase)
	httpServer := server.NewHTTPServer(confServer, application, bqbService, voiceService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
