// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.9
// source: wxxcx/v1/bqb.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBqbIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid     string `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sign      string `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *GetBqbIndexRequest) Reset() {
	*x = GetBqbIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxxcx_v1_bqb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBqbIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBqbIndexRequest) ProtoMessage() {}

func (x *GetBqbIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxxcx_v1_bqb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBqbIndexRequest.ProtoReflect.Descriptor instead.
func (*GetBqbIndexRequest) Descriptor() ([]byte, []int) {
	return file_wxxcx_v1_bqb_proto_rawDescGZIP(), []int{0}
}

func (x *GetBqbIndexRequest) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *GetBqbIndexRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GetBqbIndexRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type GetBqbIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*GetBqbIndexReply_Info `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *GetBqbIndexReply) Reset() {
	*x = GetBqbIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxxcx_v1_bqb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBqbIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBqbIndexReply) ProtoMessage() {}

func (x *GetBqbIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxxcx_v1_bqb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBqbIndexReply.ProtoReflect.Descriptor instead.
func (*GetBqbIndexReply) Descriptor() ([]byte, []int) {
	return file_wxxcx_v1_bqb_proto_rawDescGZIP(), []int{1}
}

func (x *GetBqbIndexReply) GetResults() []*GetBqbIndexReply_Info {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetBqbListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid     string `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sign      string `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	Type      string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Page      uint64 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  uint64 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *GetBqbListRequest) Reset() {
	*x = GetBqbListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxxcx_v1_bqb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBqbListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBqbListRequest) ProtoMessage() {}

func (x *GetBqbListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxxcx_v1_bqb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBqbListRequest.ProtoReflect.Descriptor instead.
func (*GetBqbListRequest) Descriptor() ([]byte, []int) {
	return file_wxxcx_v1_bqb_proto_rawDescGZIP(), []int{2}
}

func (x *GetBqbListRequest) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *GetBqbListRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GetBqbListRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *GetBqbListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetBqbListRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBqbListRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetBqbListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*GetBqbListReply_Info `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *GetBqbListReply) Reset() {
	*x = GetBqbListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxxcx_v1_bqb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBqbListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBqbListReply) ProtoMessage() {}

func (x *GetBqbListReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxxcx_v1_bqb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBqbListReply.ProtoReflect.Descriptor instead.
func (*GetBqbListReply) Descriptor() ([]byte, []int) {
	return file_wxxcx_v1_bqb_proto_rawDescGZIP(), []int{3}
}

func (x *GetBqbListReply) GetResults() []*GetBqbListReply_Info {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetBqbIndexReply_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ImagePath string `protobuf:"bytes,3,opt,name=image_path,proto3" json:"image_path,omitempty"`
	Num       uint64 `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GetBqbIndexReply_Info) Reset() {
	*x = GetBqbIndexReply_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxxcx_v1_bqb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBqbIndexReply_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBqbIndexReply_Info) ProtoMessage() {}

func (x *GetBqbIndexReply_Info) ProtoReflect() protoreflect.Message {
	mi := &file_wxxcx_v1_bqb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBqbIndexReply_Info.ProtoReflect.Descriptor instead.
func (*GetBqbIndexReply_Info) Descriptor() ([]byte, []int) {
	return file_wxxcx_v1_bqb_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetBqbIndexReply_Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBqbIndexReply_Info) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetBqbIndexReply_Info) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *GetBqbIndexReply_Info) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type GetBqbListReply_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ImagePath string `protobuf:"bytes,3,opt,name=image_path,proto3" json:"image_path,omitempty"`
}

func (x *GetBqbListReply_Info) Reset() {
	*x = GetBqbListReply_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxxcx_v1_bqb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBqbListReply_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBqbListReply_Info) ProtoMessage() {}

func (x *GetBqbListReply_Info) ProtoReflect() protoreflect.Message {
	mi := &file_wxxcx_v1_bqb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBqbListReply_Info.ProtoReflect.Descriptor instead.
func (*GetBqbListReply_Info) Descriptor() ([]byte, []int) {
	return file_wxxcx_v1_bqb_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetBqbListReply_Info) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBqbListReply_Info) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetBqbListReply_Info) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

var File_wxxcx_v1_bqb_proto protoreflect.FileDescriptor

var file_wxxcx_v1_bqb_proto_rawDesc = []byte{
	0x0a, 0x12, 0x77, 0x78, 0x78, 0x63, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x71, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x77, 0x78, 0x78, 0x63, 0x78, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x42, 0x71, 0x62, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0xaf, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42,
	0x71, 0x62, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x77, 0x78, 0x78, 0x63, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x71, 0x62, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x60, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0xa0, 0x01, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x42, 0x71, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x97, 0x01, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x42, 0x71, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x38, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x78, 0x78, 0x63, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x71, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x4a, 0x0a, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x32, 0x98, 0x02, 0x0a, 0x03, 0x42, 0x71, 0x62, 0x12, 0x61,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x71, 0x62, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x2e,
	0x77, 0x78, 0x78, 0x63, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x71, 0x62, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x78,
	0x78, 0x63, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x71, 0x62, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12,
	0x10, 0x2f, 0x77, 0x78, 0x78, 0x63, 0x78, 0x2f, 0x62, 0x71, 0x62, 0x2f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x5d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x71, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1b, 0x2e, 0x77, 0x78, 0x78, 0x63, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x71,
	0x62, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x77,
	0x78, 0x78, 0x63, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x71, 0x62, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12,
	0x0f, 0x2f, 0x77, 0x78, 0x78, 0x63, 0x78, 0x2f, 0x62, 0x71, 0x62, 0x2f, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x4f, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11,
	0x12, 0x0f, 0x2f, 0x77, 0x78, 0x78, 0x63, 0x78, 0x2f, 0x62, 0x71, 0x62, 0x2f, 0x70, 0x69, 0x6e,
	0x67, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x53, 0x75, 0x4b, 0x61, 0x69, 0x46, 0x65, 0x69, 0x2f, 0x67, 0x6f, 0x2d, 0x77, 0x78, 0x78, 0x63,
	0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x78, 0x78, 0x63, 0x78, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wxxcx_v1_bqb_proto_rawDescOnce sync.Once
	file_wxxcx_v1_bqb_proto_rawDescData = file_wxxcx_v1_bqb_proto_rawDesc
)

func file_wxxcx_v1_bqb_proto_rawDescGZIP() []byte {
	file_wxxcx_v1_bqb_proto_rawDescOnce.Do(func() {
		file_wxxcx_v1_bqb_proto_rawDescData = protoimpl.X.CompressGZIP(file_wxxcx_v1_bqb_proto_rawDescData)
	})
	return file_wxxcx_v1_bqb_proto_rawDescData
}

var file_wxxcx_v1_bqb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wxxcx_v1_bqb_proto_goTypes = []interface{}{
	(*GetBqbIndexRequest)(nil),    // 0: wxxcx.v1.GetBqbIndexRequest
	(*GetBqbIndexReply)(nil),      // 1: wxxcx.v1.GetBqbIndexReply
	(*GetBqbListRequest)(nil),     // 2: wxxcx.v1.GetBqbListRequest
	(*GetBqbListReply)(nil),       // 3: wxxcx.v1.GetBqbListReply
	(*GetBqbIndexReply_Info)(nil), // 4: wxxcx.v1.GetBqbIndexReply.Info
	(*GetBqbListReply_Info)(nil),  // 5: wxxcx.v1.GetBqbListReply.Info
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_wxxcx_v1_bqb_proto_depIdxs = []int32{
	4, // 0: wxxcx.v1.GetBqbIndexReply.results:type_name -> wxxcx.v1.GetBqbIndexReply.Info
	5, // 1: wxxcx.v1.GetBqbListReply.results:type_name -> wxxcx.v1.GetBqbListReply.Info
	0, // 2: wxxcx.v1.Bqb.GetBqbIndex:input_type -> wxxcx.v1.GetBqbIndexRequest
	2, // 3: wxxcx.v1.Bqb.GetBqbList:input_type -> wxxcx.v1.GetBqbListRequest
	6, // 4: wxxcx.v1.Bqb.Ping:input_type -> google.protobuf.Empty
	1, // 5: wxxcx.v1.Bqb.GetBqbIndex:output_type -> wxxcx.v1.GetBqbIndexReply
	3, // 6: wxxcx.v1.Bqb.GetBqbList:output_type -> wxxcx.v1.GetBqbListReply
	6, // 7: wxxcx.v1.Bqb.Ping:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wxxcx_v1_bqb_proto_init() }
func file_wxxcx_v1_bqb_proto_init() {
	if File_wxxcx_v1_bqb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wxxcx_v1_bqb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBqbIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxxcx_v1_bqb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBqbIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxxcx_v1_bqb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBqbListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxxcx_v1_bqb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBqbListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxxcx_v1_bqb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBqbIndexReply_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxxcx_v1_bqb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBqbListReply_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wxxcx_v1_bqb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wxxcx_v1_bqb_proto_goTypes,
		DependencyIndexes: file_wxxcx_v1_bqb_proto_depIdxs,
		MessageInfos:      file_wxxcx_v1_bqb_proto_msgTypes,
	}.Build()
	File_wxxcx_v1_bqb_proto = out.File
	file_wxxcx_v1_bqb_proto_rawDesc = nil
	file_wxxcx_v1_bqb_proto_goTypes = nil
	file_wxxcx_v1_bqb_proto_depIdxs = nil
}
