// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/SuKaiFei/go-wxxcx/internal/biz"
	"github.com/SuKaiFei/go-wxxcx/internal/conf"
	"github.com/SuKaiFei/go-wxxcx/internal/data"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "image/jpeg"
	_ "image/png"
)

// Injectors from wire.go:

func NewTestUnitTestSvcService(server *conf.Server, logger log.Logger, bootstrap *conf.Bootstrap, confData *conf.Data, application *conf.Application) (*unitTestSvc, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	biaoQingBaoRepo := data.NewBqbRepo(dataData, logger)
	biaoQingBaoUseCase := biz.NewBiaoQingBaoUseCase(biaoQingBaoRepo, logger)
	bqbService := NewBqbService(biaoQingBaoUseCase)
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUseCase := biz.NewArticleUseCase(articleRepo, logger)
	articleService := NewArticleService(articleUseCase)
	voiceRepo := data.NewVoiceRepo(dataData, logger)
	voiceUseCase := biz.NewVoiceUseCase(voiceRepo, logger)
	voiceService := NewVoiceService(voiceUseCase)
	navigationRepo := data.NewNavigationRepo(dataData, logger)
	navigationUseCase := biz.NewNavigationUseCase(navigationRepo, logger)
	navigationService := NewNavigationService(navigationUseCase)
	wechatRepo := data.NewWechatRepo(dataData, logger)
	wechatUseCase := biz.NewWechatUseCase(logger, application, wechatRepo)
	wechatMpService := NewWechatMpService(wechatUseCase)
	wechatOcService, cleanup2, err := NewWechatOcService(wechatUseCase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	imageUseCase := biz.NewImageUseCase(logger)
	imageService := NewImageService(imageUseCase, application)
	musicRepo := data.NewMusicRepo(dataData, logger)
	musicUseCase := biz.NewMusicUseCase(musicRepo, logger)
	musicService := NewMusicService(musicUseCase)
	chatGPTRepo := data.NewChatGPTRepo(dataData, logger)
	chatGPTUseCase := biz.NewChatGPTUseCase(chatGPTRepo, application, logger)
	chatGptService := NewChatGptService(chatGPTUseCase)
	communityRepo := data.NewCommunityRepo(dataData, logger)
	communityUseCase := biz.NewCommunityUseCase(communityRepo, logger)
	cosUseCase := biz.NewCosUseCase(application, logger)
	communityService := NewCommunityService(communityUseCase, cosUseCase, wechatUseCase)
	serviceUnitTestSvc := &unitTestSvc{
		bqbSvc:        bqbService,
		articleSvc:    articleService,
		voiceSvc:      voiceService,
		navigationSvc: navigationService,
		wechatMpSvc:   wechatMpService,
		wechatOcSvc:   wechatOcService,
		imageSvc:      imageService,
		musicSvc:      musicService,
		chatGptSvc:    chatGptService,
		communitySvc:  communityService,
	}
	return serviceUnitTestSvc, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type unitTestSvc struct {
	bqbSvc        *BqbService
	articleSvc    *ArticleService
	voiceSvc      *VoiceService
	navigationSvc *NavigationService
	wechatMpSvc   *WechatMpService
	wechatOcSvc   *WechatOcService
	imageSvc      *ImageService
	musicSvc      *MusicService
	chatGptSvc    *ChatGptService
	communitySvc  *CommunityService
}
