// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/SuKaiFei/go-wxxcx/internal/biz"
	"github.com/SuKaiFei/go-wxxcx/internal/conf"
	"github.com/SuKaiFei/go-wxxcx/internal/data"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func NewTestUnitTestSvcService(server *conf.Server, logger log.Logger, bootstrap *conf.Bootstrap, confData *conf.Data) (*unitTestSvc, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	biaoQingBaoRepo := data.NewBqbRepo(dataData, logger)
	biaoQingBaoUsecase := biz.NewBiaoQingBaoUsecase(biaoQingBaoRepo, logger)
	bqbService := NewBqbService(biaoQingBaoUsecase)
	serviceUnitTestSvc := &unitTestSvc{
		bqbSvc: bqbService,
	}
	return serviceUnitTestSvc, func() {
		cleanup()
	}, nil
}

// wire.go:

type unitTestSvc struct {
	bqbSvc *BqbService
}
