// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/SuKaiFei/go-wxxcx/internal/biz"
	"github.com/SuKaiFei/go-wxxcx/internal/conf"
	"github.com/SuKaiFei/go-wxxcx/internal/data"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func NewTestUnitTestSvcService(server *conf.Server, logger log.Logger, bootstrap *conf.Bootstrap, confData *conf.Data, application *conf.Application) (*unitTestSvc, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	biaoQingBaoRepo := data.NewBqbRepo(dataData, logger)
	biaoQingBaoUseCase := biz.NewBiaoQingBaoUseCase(biaoQingBaoRepo, logger)
	bqbService := NewBqbService(biaoQingBaoUseCase)
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUseCase := biz.NewArticleUseCase(articleRepo, logger)
	articleService := NewArticleService(articleUseCase)
	voiceRepo := data.NewVoiceRepo(dataData, logger)
	voiceUseCase := biz.NewVoiceUseCase(voiceRepo, logger)
	voiceService := NewVoiceService(voiceUseCase)
	navigationRepo := data.NewNavigationRepo(dataData, logger)
	navigationUseCase := biz.NewNavigationUseCase(navigationRepo, logger)
	navigationService := NewNavigationService(navigationUseCase)
	wechatMpUseCase := biz.NewWechatMpUseCase(logger, application)
	wechatMpService := NewWechatMpService(wechatMpUseCase)
	serviceUnitTestSvc := &unitTestSvc{
		bqbSvc:        bqbService,
		articleSvc:    articleService,
		voiceSvc:      voiceService,
		navigationSvc: navigationService,
		wechatMpSvc:   wechatMpService,
	}
	return serviceUnitTestSvc, func() {
		cleanup()
	}, nil
}

// wire.go:

type unitTestSvc struct {
	bqbSvc        *BqbService
	articleSvc    *ArticleService
	voiceSvc      *VoiceService
	navigationSvc *NavigationService
	wechatMpSvc   *WechatMpService
}
