server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
data:
  redis:
    addr: 127.0.0.1:6379
    password: 123456
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test

application:
  mp:
    appid:
      id: appid
      key: app-key
      name: app-name